name: Build main and tests
run-name: ${{ github.actor }} compiling based on CMakeLists.txt
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build main.cpp
        run: |
          cmake -H. -B_build -DBUILD_MAIN=ON
          cmake --build _build
      - name: Test if main.cpp actually present
        run: ./_build/main_test
      - name: Make artifact from compiled main
        uses: actions/upload-artifact@v4
        with:
          name: compiled_main_cpp
          path: _build/main
