name: Build main and tests
run-name: ${{ github.actor }} compiling based on CMakeLists.txt
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Config main.cpp and tests
        run: cmake -H. -B_build
      - name: Build main.cpp and tests
        run: cmake --build _build
      - name: Run tests
        run: cmake --build _build --target test -- ARGS=--verbose
      - name: Test if main.cpp actually present
        run: ./_build/main_test
      - name: Make artifact from compiled main
        uses: actions/upload-artifact@v4
        with:
          name: compiled_main_cpp
          path: _build
